type: rpm-ostree
repos:
  # - https://copr.fedorainfracloud.org/coprs/sukhmeet/RyzenAdj/repo/fedora-%OS_VERSION%/sukhmeet-RyzenAdj-fedora-%OS_VERSION%.repo
  - https://download.copr.fedorainfracloud.org/results/kylegospo/bazzite/fedora-%OS_VERSION%-x86_64/  
install:
  - ryzenadj
remove:
