type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
  #- https://copr.fedorainfracloud.org/coprs/sukhmeet/RyzenAdj/repo/fedora-%OS_VERSION%/sukhmeet-RyzenAdj-fedora-%OS_VERSION%.repo
    
install:
  - corectrl
  - kcalc
  - grubby
  - neofetch
  - virt-manager
  - coolercontrol
  - protontricks
  #- ryzenadj
  - binutils
  - gamescope
remove:
  - krfb
  - krfb-libs
  - xwaylandvideobridge
  - plasma-discover-notifier
  - vim-minimal
  - kmousetool
  - kwrite
  - vim-enhanced
  #- vim
  - icoutils
  #- yad
  - filelight
