type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
  #- https://copr.fedorainfracloud.org/coprs/sukhmeet/RyzenAdj/repo/fedora-%OS_VERSION%/sukhmeet-RyzenAdj-fedora-%OS_VERSION%.repo
    
install:
  - corectrl
  - kcalc
  - grubby
  - neofetch
  - virt-manager
  - coolercontrol
  - protontricks
  #- ryzenadj
  - binutils
  - gamescope
  - virt-install
	- libvirt-daemon-config-network
	- libvirt-daemon-kvm
	- qemu-kvm
	- virt-viewer
  - guestfs-tools
  - python3-libguestfs
  - virt-top
remove:
  - krfb
  - krfb-libs
  - xwaylandvideobridge
  - plasma-discover-notifier
  - vim-minimal
  - kmousetool
  - kwrite
  - vim-enhanced
  #- vim
  - icoutils
  #- yad
  - filelight
