type: rpm-ostree
repos:

install:
  - firefox
  - firefox-langpacks
  - gamescope
  - protontricks
remove:
  # example: removing firefox (in favor of the flatpak)
  # "firefox" is the main package, "firefox-langpacks" is a dependency
  # - firefox
  # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - steamdeck-kde-presets
  - ptyxis
  - waydroid
  - waydroid-selinux
  - discover-overlay
  #- qsynth
  #- system76-scheduler
  #- steam
